"use client";

export const mockUsers = [
    {
      id: 1,
      name: "Nahian",
      email: "test@gmail.com",
      username: "nahi",
      phone: "01308663002",
      role : "Admin",
      image : "image.png",
      status: true,
    },
    {
      id: 2,
      name: "Prosenjit",
      email: "test@gmail.com",
      username: "nahi",
      phone: "01308663002",
      role : "Admin",
      image : "image.png",
      status: true,
    },
    {
      id: 3,
      name: "Misu",
      email: "test@gmail.com",
      username: "nahi",
      phone: "01308663002",
      role : "Admin",
      image : "image.png",
      status: true,
    },
    {
      id: 4,
      name: "Farid uddin",
      email: "test@gmail.com",
      username: "nahi",
      phone: "01308663002",
      role : "Admin",
      image : "image.png",
      status: true,
    },
    {
      id: 5,
      name: "Namian",
      email: "test@gmail.com",
      username: "nahi",
      phone: "01308663002",
      role : "Admin",
      image : "image.png",
      status: true,
    },
    {
      id: 6,
      name: "Nipu",
      email: "test@gmail.com",
      username: "nahi",
      phone: "01308663002",
      role : "Admin",
      image : "image.png",
      status: true,
    },
    {
      id: 7,
      name: "Namian",
      email: "test@gmail.com",
      username: "nahi",
      phone: "01308663002",
      role : "Admin",
      image : "image.png",
      status: true,
    },
    {
      id: 8,
      name: "Namian",
      email: "test@gmail.com",
      username: "nahi",
      phone: "01308663002",
      role : "Admin",
      image : "image.png",
      status: true,
    },
    {
      id: 9,
      name: "Namian",
      email: "test@gmail.com",
      username: "nahi",
      phone: "01308663002",
      role : "Admin",
      image : "image.png",
      status: true,
    },
    {
      id:10,
      name: "Namian",
      email: "test@gmail.com",
      username: "nahi",
      phone: "01308663002",
      role : "Admin",
      image : "image.png",
      status: true,
    },
    {
      id: 11,
      name: "Namian",
      email: "test@gmail.com",
      username: "nahi",
      phone: "01308663002",
      role : "Admin",
      image : "image.png",
      status: true,
    },
    {
      id: 12,
      name: "Namian",
      email: "test@gmail.com",
      username: "nahi",
      phone: "01308663002",
      role : "Admin",
      image : "image.png",
      status: true,
    }
  ];