import type { Metadata } from "next";
import "./globals.css";
import SideBar from "@/components/SideBar";
import Navabar from "@/components/Navabar";
import { ThemeProvider } from "@/components/providers/ThemeProvider";
import { SidebarProvider } from "@/components/ui/sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="">
        <ThemeProvider 
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
          >
          <div className="bg-red-400 text-white">
            <SidebarProvider>
              <SideBar />
              <main className="w-full">
                <Navabar />
                <div className="px-4">{children}</div>
              </main>
            </SidebarProvider>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}